### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by 2204852** [crunchy-labs/crunchy-cli#358] opened 2024-03-16 13:20 UTC
dlc archive -a en-US -s all -r 1080p -o "{series_name} S{season_number}E{episode_number} - {title} [{height}p] [{audio}].mkv" -t 20 -m audio --include-fonts --skip-existing --skip-specials -y https://www.crunchyroll.com/series/GQWH0M1XK/the-weakest-tamer-began-a-journey-to-pick-up-trash
:: → Series The Weakest Tamer Began a Journey to Pick Up Trash is not available with ar-ME, ca-ES, en-IN, es-LA, hi-IN, ja-JP, ko-KR, pl-PL, pt-PT, ta-IN, te-IN, tr-TR, zh-CN, zh-CN, zh-TW subtitles
:: ✔ Loaded series information for url 1                                        :: The Weakest Tamer Began a Journey to Pick Up Trash Season 1 (The Weakest Tamer Began a Journey to Pick Up Trash (English Dub))
:: 	1. On a Journey Alone » S01E01
:: 	2.  » S01E02
:: 	3. Toward Those Remembered Days » S01E03
:: 	4. Toward an Unexpected Situation » S01E04
:: 	5. To Latome Village » S01E05
:: 	6. To Travel Beyond Imagination » S01E06
:: 	7. On a Path to Adventure » S01E07
:: 	8. To a Dangerous Town » S01E08
:: 	9. Toward a Confrontation with the Organization » S01E09
:: 	10.  » S01E10
:: An error occurred: parse error HEAD: Expecting </META> found </HEAD> (https://pl.crunchyroll.com/evs3/2352a0930dc7cad38d3faf21265e927e/assets/a3cb26d4d8958ef7a369bee30ca11d06_,5393889.mp4,5393890.mp4,5393888.mp4,5393886.mp4,5393887.mp4,.urlset/manifest.mpd?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy8yMzUyYTA5MzBkYzdjYWQzOGQzZmFmMjEyNjVlOTI3ZS9hc3NldHMvYTNjYjI2ZDRkODk1OGVmN2EzNjliZWUzMGNhMTFkMDZfLDUzOTM4ODkubXA0LDUzOTM4OTAubXA0LDUzOTM4ODgubXA0LDUzOTM4ODYubXA0LDUzOTM4ODcubXA0LC51cmxzZXQvbWFuaWZlc3QubXBkIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzEwNzY3ODUzfX19XX0_&Signature=WrMHLCn4Wcfkb4~ML1ZBcTiPQu-kPnvj708zlqsjSwbu0Rh8b-JTFpNhG5E-2J9EQDsHwQ1PUY2rkFnri4B-wBDMFHMEOcMwoPYGuuIhkyvD6h2SgeT~8AXkmIPbxqUh0LnoL-49V4RP5dT4bVs-AqfgEYB7m3kvC0IiUPRWsWcelvu6mIESQvHSu4gTHHn-adfk~7pz6M2rCB4AKNGLaWXJaPeD8Ske714rNdpVzoIHya8DSmaUJk-DFdnviN-lf-1Bz-NqiMT7SkJB7DX8UQMm98U5TNTbM8ervrBwPlINkK~-fNqhWnFJuuZDF36t~K1EpPLiIk6Qw0vfFZ5BSw__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: QeERXHugEdHT8GnB5R8Ye_qG1UdA1pxyakmnH3OnREvBUj93VX40qQ==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
![Screenshot_20240316_184805_Brave](https://github.com/crunchy-labs/crunchy-cli/assets/154334918/30baf21f-ab9e-4c78-af97-92f82dd1bedd)

**Comment by 2204852** [comment] 2024-03-16 13:22
-

**Comment by Denoder** [comment] 2024-03-16 13:25
bruh, they literally closed your las post as duplicate of https://github.com/crunchy-labs/crunchy-cli/issues/355 - 2 hours ago

**Comment by bytedream** [comment] 2024-03-16 14:20
As said, your issue is a duplicate. I will loll into it when I have time

**Closed by bytedream** 2024-03-16 14:20 UTC
Labels: bug
