### ISSUE TITLE
Cloudfront 403 error )) please fix it

### ISSUE THREAD

**Issue by 2204852** [crunchy-labs/crunchy-cli#357] opened 2024-03-16 06:40 UTC
When I try to download an episode, I get the following error:

./crunchy-cli download https://www.crunchyroll.com/de/watch/GJWU294XK/attack-on-titan-final-season-the-final-chapters-special-1
:: √ Logging in
:: √ Parsed url 1
:: √ Loaded series information for url 1
:: Attack on Titan Season 4 (Attack on Titan Final Season (German Dub))
::      1. Erdrumoren » S04ESP1
:: An error occurred: parse error HEAD: Expecting </META> found </HEAD> (https://pl.crunchyroll.com/evs3/25c7dccaa8c6970503b348dc97d006b0/assets/604ffb646f0fc34e3a0f00307d396093_,5265820.mp4,5265821.mp4,5265819.mp4,5265817.mp4,5265818.mp4,.urlset/manifest.mpd?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy8yNWM3ZGNjYWE4YzY5NzA1MDNiMzQ4ZGM5N2QwMDZiMC9hc3NldHMvNjA0ZmZiNjQ2ZjBmYzM0ZTNhMGYwMDMwN2QzOTYwOTNfLDUyNjU4MjAubXA0LDUyNjU4MjEubXA0LDUyNjU4MTkubXA0LDUyNjU4MTcubXA0LDUyNjU4MTgubXA0LC51cmxzZXQvbWFuaWZlc3QubXBkIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzEwNTkzNzE5fX19XX0_&Signature=OOreZO8OpWmQi3UfX2zV9yK1bwK~OGQilnAyx18~7BNbDuEjmd0Xm5nmUr6flFwh40VXFGIRqjUwd1W2l-vyEm9DL9coo3pKAz10hDsSui1U4rWxNXctLF5AhI7CVKN9KKnwlgKcs1wx50h2kr6eLIq5s9sSm2tquz6e3bIDTt1OdaSlK9y4mJoNiueiK9V8DPG8bRZdKDDRaoO6~fiWVTC9qGaEbVRWTuOtc37kCpJ0~SPjlXJZP3yIGYFxIL7vC9klfMNJhw0TmGnEF3ZHdkrgyR9ykJbYfBPhKMC2nYKp~QEkyq1U6pH1VoEJiXld2j3t3nv6uZJYB4P6Okz9wA__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: zHX99stDva3I9Mq3Ila7Icvuy26WYKAZUnmWhHlE9aIkl0HTBa4B1g==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>

**Comment by bytedream** [comment] 2024-03-16 11:08
Duplicate of #335

**Closed** 2024-03-16 11:08 UTC
Labels: bug
