### ISSUE TITLE
No matching stream found also if available

### ISSUE THREAD

**Issue by aniplayIt** [crunchy-labs/crunchy-cli#81] opened 2022-12-12 10:20 UTC
**Describe the bug**
I'm trying to download an episode with the command below. The episode is 
- available
- 1080p
- with italian subs

I expect to get errors until the episode is not available obviously, but once they publish it I continue to recieve the same error:
Process detail: 
- Parsing url 1
➞ Failed to parse url 1
➞ An error occurred: error while receiving format for Clutch! Robin, un demone in forma umana!: no matching stream found

After some hours without a specific reason the download works.

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy download -a ja-JP -s it-IT -o one_piece_1044.mp4 -r 1080p https://www.crunchyroll.com/it/series/GRMG8ZQZR/one-piece[S13E1044]

I also tried to append a timestamp to get rid of some weird cache problem:
$ crunchy download -a ja-JP -s it-IT -o one_piece_1044.mp4 -r 1080p https://www.crunchyroll.com/it/series/GRMG8ZQZR/one-piece?t=1670832000279[S13E1044]
```

**Expected behavior**
Download the episode

**Screenshots**

**Client (please complete the following information):**
 - OS: Linux
 - Version 2.3.6

**Additional context**
**IMPORTANT**
If I try to start the download from another pc with a clean version of crunchy-cli it works

**Comment by ByteDream** [comment] 2022-12-12 21:06
Was this the first incident or has this already occurred multiple times?
This _may_ (hopefully) be a one-time bug if this only occurred once.

**Comment by aniplayIt** [comment] 2022-12-12 21:22
> Was this the first incident or has this already occurred multiple times? This _may_ (hopefully) be a one-time bug if this only occurred once.

It already happend multiple times. For such episodes, they become available after some days while they were already present. For example I still cannot download the mentioned One Piece episode from that pc but I can from another one. It happened last week with Boruto too.

**Comment by aniplayIt** [comment] 2022-12-12 21:45
Another strange behaviour I noticed is that an episode is already available and watchable on crunchyroll. In this case Dr. Stone Ep 1 Italian Dubbed, but the downloader keeps telling me Stone World has no it-IT audio, using ja-JP as fallback

**Comment by ByteDream** [comment] 2022-12-12 21:56
> > Was this the first incident or has this already occurred multiple times? This _may_ (hopefully) be a one-time bug if this only occurred once.
> 
> It already happend multiple times. For such episodes, they become available after some days while they were already present. For example I still cannot download the mentioned One Piece episode from that pc but I can from another one. It happened last week with Boruto too.

This is indeed very strange. This sounds like a caching problem but the cli doesn't cache anything nor should your OS / computer do this. Maybe re-logging in solves the problem.

**Comment by ByteDream** [comment] 2022-12-12 22:03
> Another strange behaviour I noticed is that an episode is already available and watchable on crunchyroll. In this case Dr. Stone Ep 1 Italian Dubbed, but the downloader keeps telling me Stone World has no it-IT audio, using ja-JP as fallback

With `crunchy download -a it-IT https://www.crunchyroll.com/series/GYEXQKJG6/dr-stone[S1E1]` the download works for me.

**Comment by aniplayIt** [comment] 2022-12-12 22:20
> > Another strange behaviour I noticed is that an episode is already available and watchable on crunchyroll. In this case Dr. Stone Ep 1 Italian Dubbed, but the downloader keeps telling me Stone World has no it-IT audio, using ja-JP as fallback
> 
> With `crunchy download -a it-IT https://www.crunchyroll.com/series/GYEXQKJG6/dr-stone[S1E1]` the download works for me.

And it just did for me, but the episode is available since 2 hours ago

**Comment by aniplayIt** [comment] 2022-12-12 22:21
> > > Was this the first incident or has this already occurred multiple times? This _may_ (hopefully) be a one-time bug if this only occurred once.
> > 
> > 
> > It already happend multiple times. For such episodes, they become available after some days while they were already present. For example I still cannot download the mentioned One Piece episode from that pc but I can from another one. It happened last week with Boruto too.
> 
> This is indeed very strange. This sounds like a caching problem but the cli doesn't cache anything nor should your OS / computer do this. Maybe re-logging in solves the problem.

Already tried to restart and relogin. Still cannot download One Piece

**Comment by aniplayIt** [comment] 2022-12-13 16:29
Do you have any suggestion on how to fix this. After 3 days I still receive this message:
crunchy download -a ja-JP -s it-IT -o episode.mp4 -r 1080p https://www.crunchyroll.com/it/series/GRMG8ZQZR/one-piece\[S13E1044\]
➞ Failed to parse url 1
➞ An error occurred: error while receiving format for Clutch! Robin, un demone in forma umana!: no matching stream found

**Comment by aniplayIt** [comment] 2022-12-14 11:00
I'm here to keep you updated. In this case:
crunchy download -a ja-JP -s it-IT -o ep.mp4 -r 720p [https://www.crunchyroll.com/it/series/GZJH3DJ8E/the-daily-life-of-the-immortal-king[S3E12]
I'm not able to download it anywhere also even the episode is available since yesterday. 
Can you please check if it's the same on your side?

**Comment by ByteDream** [comment] 2022-12-14 17:22
Can confirm this. Here we have a complete different problem. The anime is not japense but chinese. So the right command would be `crunchy download -a zh-CN -s it-IT -o ep.mp4 -r 720p https://www.crunchyroll.com/it/series/GZJH3DJ8E/the-daily-life-of-the-immortal-king[S3E12]` (`zh-CN` = chinese). Then the cli finds the correct episode. Buut... even though the audio is chinese (at least it sounds like that) Crunchyroll marks it as japanese which causes the cli to not find the correct stream.

**Comment by aniplayIt** [comment] 2022-12-14 17:26
Mm ok good to know. However I'm still trying to download one piece 😅

**Comment by ByteDream** [comment] 2022-12-14 17:35
I tried to reproduce the behavior that it downloads from one PC but not from another but hadn't any success yet :/

**Comment by aniplayIt** [comment] 2022-12-14 19:27
Something is missing here. Today I have tried for 2 hours to download another episode, no episodes are matching the given filter but it's not true. I have no clue on why it says that..

**Comment by aniplayIt** [comment] 2022-12-14 22:40
@ByteDream I was wondering, I don't know the actual architecture of crunchyroll but could it be that the downloader is asking for the episode to a node where data is still not replicated?

**Comment by ByteDream** [comment] 2022-12-14 23:31
This might be the case, I hadn't the time to test this yet.
Crunchyroll provides two different stream formats (HLS and DASH). The crunchyroll website uses the DASH stream and the cli HLS (as this format is simpler and easier to implement). It might be that they generate the HLS streams later than the DASH equivalent. I'm planning to adopt DASH streams in the cli soon, so if that's the cause of the issue it's fixed with this adoption. If not, I have to search somewhere else for the problem.

**Comment by aniplayIt** [comment] 2022-12-14 23:34
I was trying to test it also with a proxy but I didn't figure out how to pass the proxy arg. I get a ➞ Unexpected error: interface conversion: error is *url.Error, not *crunchyroll.RequestError.
Can you tell me please how to pass it?

**Comment by ByteDream** [comment] 2022-12-14 23:41
What was the (complete) command you were using?

**Comment by aniplayIt** [comment] 2022-12-14 23:42
It is not documented so I just tried with
crunchy download -p ip.ip.ip.ip -a ja-JP -s it-IT -o episode.mp4 -r best https://www.crunchyroll.com/it/series/GRMG8ZQZR/one-piece[S13E1044]

**Comment by ByteDream** [comment] 2022-12-14 23:52
I think you have to specify the protocol and port too, so `http://ip.ip.ip.ip:port` or `socks5://ip.ip.ip.ip:port`.
TBH I never really tested this xD. The only time I tested this I used unstable public proxies which resolved connection errors.

**Comment by aniplayIt** [comment] 2022-12-16 21:00
I tested the v3 with that infamous one piece episode. Now I get a different error: 
Episode 1044 (Clutch! A Demon Incarnate, Robin!) of season 13 (One Piece: WANO KUNI (892-Current)) of One Piece has no it-IT subtitles
But it obvioulsy has IT subtitles 🫤

**Comment by adracea** [comment] 2022-12-24 13:57
> I tested the v3 with that infamous one piece episode. Now I get a different error: Episode 1044 (Clutch! A Demon Incarnate, Robin!) of season 13 (One Piece: WANO KUNI (892-Current)) of One Piece has no it-IT subtitles But it obvioulsy has IT subtitles 🫤

>One Piece has no it-IT subtitles But it obvioulsy has IT subtitles 
Hey @aniplayIt , I tried digging on this issue today and I honestly am not able to see any subs for OnePiece other than English for some reason ? Crunchyroll might be pulling something shady as they have started reporting ja-JP and even zh-CN locales as en-US .

**Comment by ByteDream** [comment] 2023-01-03 15:20
It seems that the subtitles are geo restricted as I can only access German subtitles.

**Comment by aniplayIt** [comment] 2023-01-04 12:28
Yes correct. Fixed using a VPN. This does not depend on the downloader so I'm closing the issue

**Comment by aniplayIt** [comment] 2023-01-06 17:37
I'm reopening this so maybe you can help me figure out how to download this. 

- I'm using release v3.0.0-dev.6
- Episode has japanese audio and italian subtitles
- My geo is IT
- Account is premium

crunchy --credentials xxx:xxx --lang it-IT download -a ja-JP -s it-IT -o episode.ts -r best https://www.crunchyroll.com/it/watch/G2XU0Q9EN/please-eat-me-up-great-evil-dragon
:: ✔ Logged in                                                                  
:: ✔ Parsed url 1                                                               
:: ✔ Fetching series details                                                    
:: a unexpected error occurred: could not find any stream with hardsub locale 'it-IT'

**Comment by ByteDream** [comment] 2023-01-06 18:07
That's interesting. I can download it without problems. Does the issue still exist for you?

**Comment by aniplayIt** [comment] 2023-01-07 17:32
@ByteDream now I can download it but the audio is chinese...

**Comment by ByteDream** [comment] 2023-01-08 19:56
The anime shouldn't have a chinese dub at all 🤔

**Comment by aniplayIt** [comment] 2023-01-11 00:40
The animes
- The Last Summoner
- A Herbivorous Dragon of 5,000 Years Gets Unfairly Villainized
are originally with chinese audio. Now they are dubbing them in japanese, but whene I try to download any of the two, I get chinese audio

**Comment by aniplayIt** [comment] 2023-01-13 00:27
Here we go again
crunchy --credentials xxx:xxx --lang it-IT download -a ja-JP -s it-IT -o  episode.ts -r 1080p https://www.crunchyroll.com/it/series/GQWH0M455/dont-toy-with-me-miss-nagatoro\[S2E2\]
:: ✔ Logged in                                                                                                                                                                                                                                :: ✔ Parsed url 1                                                                                                                                                                                                                             :: ✔ Fetching series details                                                                                                                                                                                                                  :: a unexpected error occurred: could not find any stream with hardsub locale 'it-IT'

<img width="1680" alt="immagine" src="https://user-images.githubusercontent.com/100148780/212209166-7f071c7d-b007-46d3-839a-4b4dfab9d8dd.png">

**Comment by ByteDream** [comment] 2023-01-13 10:58
Now I can reproduce :o

**Comment by ByteDream** [comment] 2023-01-13 11:04
Okay, this is the point where `ffmpeg` is/will be mandatory for download too.
Crunchyroll provides subtitles in two ways: Burnt into the video and as file which only contains the subtitle. It seems that they're moving away from burning them into the video? The download command always uses the video with subtitles burnt in but Crunchyroll fails to deliver those kind of videos for every language. Italian is one of the languages which does not always receive a burnt-in variant, which is the cause of your issue.

**Comment by aniplayIt** [comment] 2023-01-13 11:58
Ok so you'll add some flag to tell ffmpeg to re-encode the episode with burnt-in subtitles?

**Comment by ByteDream** [comment] 2023-01-13 12:22
Yep

**Closed** 2023-01-13 23:03 UTC
Labels: bug
