### ISSUE TITLE
:: An error occurred: builder error

### ISSUE THREAD

**Issue by sergiohzph** [crunchy-labs/crunchy-cli#379] opened 2024-04-14 17:26 UTC
![image](https://github.com/crunchy-labs/crunchy-cli/assets/138529583/c00a58e7-48d2-406f-a94b-8d26fb859ea1)

I logged in, I put the command `.\crunchy-cli-v3.4.2-windows-x86_64.exe download https://www.crunchyroll.com/series/G3KHEVDJ7/the-apothecary-diaries` and I get that error. What do I have to do?

**Comment by bytedream** [comment] 2024-04-14 20:09
You're probably using an account that has no premium subscription. This is the cause of the error, crunchy-cli tried to get stream information about an episode you do not have access to.
This is fixed in [v3.4.3](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.4.3), now you get a message if episodes cannot be downloaded instead of failing with the `builder error` command

**Closed by bytedream** 2024-04-14 20:09 UTC
Labels: bug

**Comment by sergiohzph** [comment] 2024-04-14 20:11
> You're probably using an account that has no premium subscription. This is the cause of the error, crunchy-cli tried to get stream information about an episode you do not have access to. This is fixed in [v3.4.3](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.4.3), now you get a message if episodes cannot be downloaded instead of failing with the `builder error` command

This anime doesn't require Premium to be watched.

**Comment by bytedream** [comment] 2024-04-14 20:21
You're trying to download the english dub of the series, it is premium only.
The first 3 episodes with japanese audio are free, you'd have to explicitly specify the japanese audio (`-a ja-JP` flag) to download them
