### ISSUE TITLE
Switch endpoint is now DRM encrypted

### ISSUE THREAD

**Issue by hajimekun** [crunchy-labs/crunchy-cli#439] opened 2024-06-19 07:02 UTC
**Describe the bug**
Not properly a bug, the streams now available on the /console endpoint is now DRM encryped

**To Reproduce**
Download a video or audio and enjoy beautiful rainbow flashes

**Client (please complete the following information):**
 - OS: Windows
 - Version: crunchy-cli 3.6.6

**Additional context**
The problem is that program not support self-providing a wvd so now is unusable

**Comment by bytedream** [comment] 2024-06-19 08:13
Duplicate of #438

**Closed by bytedream** 2024-06-19 08:13 UTC
Labels: bug

**Comment by bytedream** [comment] 2024-06-19 20:28
@hajimekun I'm sorry for changing the title/text, I thought OMA was a type. Apparently not, I just never heard of it
