### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by hazy-kun** [crunchy-labs/crunchy-cli#356] opened 2024-03-15 05:53 UTC
**Describe the bug**
```
 An error occurred: parse error HEAD: Expecting </META> found </HEAD> (https://pl.crunchyroll.com/evs3/8b85c36c0464e640964c58434e63b94b/assets/298dbf4a20f27ad127e7478f4f87dd29_,5457298.mp4,5457299.mp4,5457297.mp4,5457295.mp4,5457296.mp4,.urlset/manifest.mpd?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiaHR0cCo6Ly9wbC5jcnVuY2h5cm9sbC5jb20vZXZzMy84Yjg1YzM2YzA0NjRlNjQwOTY0YzU4NDM0ZTYzYjk0Yi9hc3NldHMvMjk4ZGJmNGEyMGYyN2FkMTI3ZTc0NzhmNGY4N2RkMjlfLDU0NTcyOTgubXA0LDU0NTcyOTkubXA0LDU0NTcyOTcubXA0LDU0NTcyOTUubXA0LDU0NTcyOTYubXA0LC51cmxzZXQvbWFuaWZlc3QubXBkIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzEwNjU0NDQ1fX19XX0_&Signature=TlNSKKx-1P2EjVd5F~pfhBK4vzBEmgvu32bdw2Kkx75ZfjKi860HoxLSOY9uASux-02r0AJnZU1DHCyP0ps9HBpMw9QFAOI3qZPpq2tD24kdEyS0~lF006W6-4PUw09fMjQaPEkunLyN627-1QFfjMMQ78hN4kmdqPPBOBm~lo-pnv4y5K6OoxWHOIm~rmGmEkLvuSt5zHY2f5Q-XolSnQ7ljrQZoKq8HZM7clX~oo-S3mzZSZbudPfDvJp8f9Y40ofvZM1HWWLx2u5wmECaBAO7UoQhXRGuPJ4HfZ~WbjkNO0b42dHyxBeKT9~MsC0VYJWQNUq0fDnyf7d6LtVzzQ__&Key-Pair-Id=APKAJMWSQ5S7ZB3MF5VA): <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: eg6Pox7NimVFJvA0DCvNeOzQ5iSrKmsyX26g3af2O0C16YPSzGqWmg==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
```

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy ...
```

**Expected behavior**

**Screenshots**

**Client (please complete the following information):**
 - OS: [Windows]
 - Version [3.3.1]

**Additional context**

**Comment by TheAznCoderPro** [comment] 2024-03-15 06:43
This is a known issue: see issue #355

**Comment by bytedream** [comment] 2024-03-15 08:26
Yes, duplicate of #355

**Closed** 2024-03-15 08:26 UTC
Labels: bug
