### ISSUE TITLE
InvalidDigit in En-US audio

### ISSUE THREAD

**Issue by yukianime** [crunchy-labs/crunchy-cli#416] opened 2024-05-12 23:35 UTC
**Describe the bug**
When I try to download chapter 3 of Lycoris Recoil (with 1 and 2 it doesn't happen) with all the subtitles and all the audios, it gives the following error:

:: Downloading subtitles    en-US (CC), en-US (CC) |                            thread 'main' panicked at /cargo/registry/src/index.crates.io-6f17d22bba15001f/rsubs-lib-0.2.1/src/vtt.rs:601:63:
called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }
stack backtrace:
   0:     0x7e2753eda471 - <unknown>
   1:     0x7e2753a2532c - <unknown>
   2:     0x7e2753eaa43e - <unknown>
   3:     0x7e2753edbd5f - <unknown>
   4:     0x7e2753edb66d - <unknown>
   5:     0x7e2753edc59a - <unknown>
   6:     0x7e2753edc0c0 - <unknown>
   7:     0x7e2753edc016 - <unknown>
   8:     0x7e2753edc003 - <unknown>
   9:     0x7e2753961d84 - <unknown>
  10:     0x7e27539621a2 - <unknown>
  11:     0x7e2753ddf2e6 - <unknown>
  12:     0x7e27539a0ca1 - <unknown>
  13:     0x7e27539ba1d4 - <unknown>
  14:     0x7e2753989e9a - <unknown>
  15:     0x7e2753b2c8e9 - <unknown>
  16:     0x7e2753b29c08 - <unknown>
  17:     0x7e2753b2b3d2 - <unknown>

Testing audio by audio individually, the problem is with the English audio with all subtitle

**To Reproduce**
the command I sue: archive -m audio -a all -s all  --output "asd.mkv" https://www.crunchyroll.com/series/G1XHJV2X9/lycoris-recoil[E3]

**Screenshots**
![imagen_2024-05-12_203403237](https://github.com/crunchy-labs/crunchy-cli/assets/163084032/550137ee-e3ac-4e48-b3d3-5dd236662c9a)

**Additional context**
I use the version "crunchy-cli-v3.6.1-linux-x86_64" running it in Google Colab
the download of the chapter goes well at first, the error appears after the end of "Downloading video"

**Comment by Frooastside** [comment] 2024-05-14 16:29
duplicate of #408

**Closed** 2024-05-14 22:16 UTC
Labels: bug
