### ISSUE TITLE
Some episodes misses some seconds at end

### ISSUE THREAD

**Issue by Kartatz** [crunchy-labs/crunchy-cli#298] opened 2024-01-03 21:31 UTC
**Describe the bug**

I'm facing a weird issue where sometimes the downloaded video misses some seconds at the end.

Here is a video which triggers this issue:

```bash
$ ffmpeg -hide_banner -i 'Butei Charter Article 1.mkv'
Input #0, matroska,webm, from 'Butei Charter Article 1.mkv':
  Metadata:
    COMPATIBLE_BRANDS: iso5dashmsix
    MAJOR_BRAND     : iso5
    MINOR_VERSION   : 1
    ENCODER         : Lavf60.20.100
  Duration: 00:24:21.16, start: 0.000000, bitrate: 3386 kb/s
  Stream #0:0: Video: h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
...
```

As can be seen, the video metadata is reporting a duration of `24:21.16`.

When trying to demux the video with ffmpeg:

```bash
ffmpeg -hide_banner -i 'Butei Charter Article 1.mkv' -c copy -f null -
...
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[out#0/null @ 0xb400007cc698f2b0] video:575194kB audio:5188kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
size=N/A time=00:16:20.56 bitrate=N/A speed= 312x    
```

The demuxing process stops at `16:20.56`. When I open the media with VLC, it plays just fine until reaching `16:20`, at which point the player abruptly closes.

This is kind of rare; it happens with about 1 out of 150 videos downloaded. Re-downloading the media generally fixes the issue.

**To Reproduce**

Here is the command I used to download this episode:

```bash
crunchy-dl archive \
    --audio 'ja-JP'  \
    --audio 'en-US'  \
    --subtitle 'en-US'  \
    --merge 'audio'  \
    --threads '13'  \
    --include-fonts  \
    --output 'Butei Charter Article 1.mkv'  \
    'https://www.crunchyroll.com/watch/GD9UVJ729/butei-charter-article-1'
```

**Client:**

 - OS: Arch Linux
 - Version crunchy-cli 3.1.1 (19935df 2023-12-30)

**Comment by bytedream** [comment] 2024-01-14 20:13
Duplicate of #271, any further conversation will take place there.
If possible, please run your command with the -v flag and paste the log output a case of missing data occurs again to #271

**Closed by bytedream** 2024-01-14 20:13 UTC
Labels: bug
