### ISSUE TITLE
Process stucked at a certain episode 

### ISSUE THREAD

**Issue by GarouTheDevil** [crunchy-labs/crunchy-cli#312] opened 2024-01-14 13:01 UTC
So i started downloading Jujutsu Kaisen s01 and i observed dl Stucked at episode 18 and after that i did a new start again and now its stucked at episode 8 and i did it again now it Stucked at episode 21

crunchy archive -o "Jujutsu-Kaisen-S01-mkv/{series_name} (呪術廻戦) S{season_number}EP{relative_sequence_number} {title} {height}p.mkv" -r 1080p -t 1500 --audio te-IN --audio ta-IN --audio hi-IN --audio en-US --audio ja-JP --subtitle en-US --merge audio https://www.crunchyroll.com/series/GRDV0019R/jujutsu-kaisen[S1]

**Comment by Penthious** [comment] 2024-01-14 13:15
I think this is related to: https://github.com/crunchy-labs/crunchy-cli/issues/310

**Comment by Penthious** [comment] 2024-01-14 13:19
My current fix is to rerun it with [S1Efailed_at] IE: [https://www.crunchyroll.com/series/GRDV0019R/jujutsu-kaisen[S1]](https://www.crunchyroll.com/series/GRDV0019R/jujutsu-kaisen%5BS1%5D)[S1E21] this will redownload starting at episode 21, or you can just add the flag --skip-existing to start where you failed as well.

**Comment by GarouTheDevil** [comment] 2024-01-14 13:52
Yes currently i am doing the same but you know it annoys me because now i am not able to dl seasons properly

**Comment by bytedream** [comment] 2024-01-14 19:34
Duplicate of #310, closing in favor of it

**Closed by bytedream** 2024-01-14 19:34 UTC
Labels: bug
