### ISSUE TITLE
Episode download gets stuck at 100%

### ISSUE THREAD

**Issue by IchBinLeoon** [crunchy-labs/crunchy-cli#90] opened 2022-12-24 15:07 UTC
**Describe the bug**
https://github.com/crunchy-labs/crunchy-cli/issues/89#issuecomment-1364523108

**To Reproduce**
Steps / command to reproduce the behavior:
```
$ crunchy download ...
$ crunchy archive ...
```

**Expected behavior**
Download the episode and continue.

**Client:**
 - OS: Windows
 - Version [v3.0.0-dev.4](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.4)

**Additional context**
Works fine with [v3.0.0-dev.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.2) according to https://github.com/crunchy-labs/crunchy-cli/issues/89#issuecomment-1364538250.

**Comment by ByteDream** [comment] 2022-12-27 18:04
This is probably caused by faadd89fffb1832126de5bfdf89dc421409535bf. The additional condition added there + unfavorable timing might be causing a dead lock there.

**Comment by ByteDream** [comment] 2023-01-03 14:10
This should be fixed in [v3.0.0-dev.5](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.0.0-dev.5).

**Closed by ByteDream** 2023-01-03 14:10 UTC
Labels: bug
