### ISSUE TITLE
invalid_client error

### ISSUE THREAD

**Issue by 1nfiniteZest** [crunchy-labs/crunchy-cli#377] opened 2024-04-11 23:16 UTC
Ive been downloading episdoes from crunchy roll a few times over the past week and everything has worked great. I keep getting this error today though. My Login info is correct. 
invalid_client (auth.obtain_access_token.client_inactive) -  (https://www.crunchyroll.com/auth/v1/token)

**Comment by bytedream** [comment] 2024-04-11 23:29
Duplicate of #375.

I assume that you're using version 3.4.1 or below. Please update to [v3.4.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.4.2), the issue is fixed there

**Closed by bytedream** 2024-04-11 23:29 UTC
Labels: bug

**Comment by 1nfiniteZest** [comment] 2024-04-12 05:34
> Duplicate of #375.
> 
> I assume that you're using version 3.4.1 or below. Please update to [v3.4.2](https://github.com/crunchy-labs/crunchy-cli/releases/tag/v3.4.2), the issue is fixed there

Thanks again mate!
