### ISSUE TITLE
To extract audio

### ISSUE THREAD

**Issue by imcrown** [crunchy-labs/crunchy-cli#434] opened 2024-06-05 17:58 UTC
Hey buddy can you add feature for only extract audio because while downloading and convert it take much time and network if we get only audio download feature so it will take less time to encoding and less network pls

**Comment by bytedream** [comment] 2024-06-05 18:46
Duplicate of #424 (TLDR; i'm still considering to add it but nothing definite yet).

See https://github.com/crunchy-labs/crunchy-cli/issues/340#issuecomment-1964870505 for a workaround with the `search` subcommand.

**Closed by bytedream** 2024-06-05 18:46 UTC
Labels: enhancement
